### ISSUE TITLE
Http2 and cache issue

### ISSUE THREAD

**Issue by yovanoc** [szmarczak/http2-wrapper#47]
I don't know if I had to put this on Got or here but there is still a problem with http2 and cache option

```
/Users/devchris/Desktop/project/node_modules/responselike/src/index.js:18
			throw new TypeError('Argument `url` should be a string');
         ^
TypeError: Argument `url` should be a string
    at new Response (/Users/devchris/Desktop/project/node_modules/responselike/src/index.js:18:10)
    at ClientRequest.handler (/Users/devchris/Desktop/project/node_modules/cacheable-request/src/index.js:89:19)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at ClientRequest.origin.emit (/Users/devchris/Desktop/project/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at /Users/devchris/Desktop/project/node_modules/http2-wrapper/source/client-request.js:319:16
    at ClientHttp2Stream.<anonymous> (/Users/devchris/Desktop/project/node_modules/http2-wrapper/source/client-request.js:262:7)
    at Object.onceWrapper (events.js:421:26)
    at ClientHttp2Stream.emit (events.js:314:20)
```

**Comment by szmarczak** [comment]
It uses `response.url` which is not documented. Fixing this rn.
