### ISSUE TITLE
urlToHttpOptions is not a function for NodeJS 14

### ISSUE THREAD

**Issue by dilame** [szmarczak/http2-wrapper#68]
Seems like it only works with NodeJS 15, because NodeJS 14 `url` don't export `urlToHttpOptions`

```
RequestError: urlToHttpOptions is not a function

    at Request._makeRequest (/Users/bowzee/WebstormProjects/igpapi/node_modules/got/dist/source/core/index.js:1177:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at new ClientRequest (/Users/bowzee/WebstormProjects/igpapi/node_modules/http2-wrapper/source/client-request.js:44:12)
    at request (/Users/bowzee/WebstormProjects/igpapi/node_modules/http2-wrapper/source/index.js:23:9)
    at Request._makeRequest (/Users/bowzee/WebstormProjects/igpapi/node_modules/got/dist/source/core/index.js:1124:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/bowzee/WebstormProjects/igpapi/node_modules/got/dist/source/core/index.js:328:17
```

**Comment by szmarczak** [comment]
That's right. It's still possible to install on lower versions but that's only so it doesn't throw when importing - for example Got imports `http2-wrapper`.

**Comment by dilame** [comment]
Thank you for your answer!
Could you please hint on how to fix it on the lower node versions?

**Comment by szmarczak** [comment]
> Could you please hint on how to fix it on the lower node versions?

It's not possible.
