### ISSUE TITLE
``got`` example does not work

### ISSUE THREAD

**Issue by ddo** [szmarczak/http2-wrapper#8]
```js
const got = require('got');
const {request} = require('http2-wrapper');

const h2got = got.extend({request});

(async () => {
	const {body} = await h2got('https://nghttp2.org/httpbin/headers');
	console.log(body);
})();
```

err

```
RequestError: Cannot read property 'on' of undefined
at EventEmitter.cacheReq.on.error (...node_modules/got/source/request-as-event-emitter.js:155:27)
at EventEmitter.emit (events.js:182:13)
at makeRequest (...node_modules/cacheable-request/src/index.js:126:9)
at get (...node_modules/cacheable-request/src/index.js:136:14)
```

**Comment by szmarczak** [comment]
It's quite stable now. The `master` branch contains many, many bug fixes and improvements.
Once I review it in the morning (it's late here), I'll release `0.4.0` :cat:

**Comment by szmarczak** [comment]
[`v0.4.0`](https://github.com/szmarczak/http2-wrapper/releases/tag/v0.4.0) is out! :)

**Comment by ddo** [comment]
👍 thanks, gonna check it soon
