### ISSUE TITLE
error RequestError: read ECONNRESET

### ISSUE THREAD

**Issue by chrislemmer** [szmarczak/http2-wrapper#82]
Hi there,

We're having a problem with the ECONNRESET. If I'm not mistaken, this error is within this plugin? It seems there is some sort of timer causing an issue?

Herewith is the full error. I've blanked out the WordPress backend URL.

`8:18:43 AM: success  gatsby-source-wordpress  Product - 398.251s - fetched 1505
8:19:34 AM: error RequestError: read ECONNRESET
8:19:34 AM:     at ClientRequest.<anonymous> (/opt/build/repo/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/index.js:956:111)
8:19:34 AM:     at Object.onceWrapper (events.js:422:26)
8:19:34 AM:     at ClientRequest.emit (events.js:327:22)
8:19:34 AM:     at ClientRequest.origin.emit (/opt/build/repo/node_modules/gatsby-source-wordpress/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
8:19:34 AM:     at TLSSocket.socketErrorListener (_http_client.js:426:9)
8:19:34 AM:     at TLSSocket.emit (events.js:315:20)
8:19:34 AM:     at emitErrorNT (internal/streams/destroy.js:92:8)
8:19:34 AM:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
8:19:34 AM:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
8:19:34 AM:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
8:19:34 AM:   code: 'ECONNRESET',
8:19:34 AM:   timings: {
8:19:34 AM:     start: 1633673973975,
8:19:34 AM:     socket: 1633673973975,
8:19:34 AM:     lookup: 1633673973999,
8:19:34 AM:     connect: 1633673974027,
8:19:34 AM:     secureConnect: 1633673974060,
8:19:34 AM:     upload: 1633673974063,
8:19:34 AM:     response: 1633673974531,
8:19:34 AM:     end: undefined,
8:19:34 AM:     error: 1633673974552,
8:19:34 AM:     abort: 1633673974558,
8:19:34 AM:     phases: {
8:19:34 AM:       wait: 0,
8:19:34 AM:       dns: 24,
8:19:34 AM:       tcp: 28,
8:19:34 AM:       tls: 33,
8:19:34 AM:       request: 3,
8:19:34 AM:       firstByte: 468,
8:19:34 AM:       download: undefined,
8:19:34 AM:       total: 577
8:19:34 AM:     }
8:19:34 AM:   }
8:19:34 AM: }
8:19:34 AM: error Error: failed to process https://website.xyz/wp-content/uploads/2020/10/RIOLA-75X150-scaled.jpg
8:19:34 AM: RequestError: read ECONNRESET
8:19:34 AM:     at Ticket.<anonymous> (/opt/build/repo/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js:353:16)
8:19:34 AM:     at Ticket.emit (events.js:315:20)
8:19:34 AM:     at Ticket.failed (/opt/build/repo/node_modules/better-queue/lib/ticket.js:49:8)
8:19:34 AM:     at /opt/build/repo/node_modules/better-queue/lib/tickets.js:10:16
8:19:34 AM:     at Array.forEach (<anonymous>)
8:19:34 AM:     at Tickets._apply (/opt/build/repo/node_modules/better-queue/lib/tickets.js:9:16)
8:19:34 AM:     at Tickets.<computed> [as failed] (/opt/build/repo/node_modules/better-queue/lib/tickets.js:30:10)
8:19:34 AM:     at Worker.<anonymous> (/opt/build/repo/node_modules/better-queue/lib/queue.js:616:25)
8:19:34 AM:     at Worker.emit (events.js:315:20)
8:19:34 AM:     at Worker.failedTask (/opt/build/repo/node_modules/better-queue/lib/worker.js:137:10)
8:19:34 AM:     at /opt/build/repo/node_modules/better-queue/lib/worker.js:124:10
8:19:34 AM:     at Array.forEach (<anonymous>)
8:19:34 AM:     at Worker.failedBatch (/opt/build/repo/node_modules/better-queue/lib/worker.js:122:30)
8:19:34 AM:     at cb (/opt/build/repo/node_modules/better-queue/lib/worker.js:72:14)
8:19:34 AM:     at Worker.pushToQueue [as fn] (/opt/build/repo/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js:138:12)
8:19:34 AM:     at runMicrotasks (<anonymous>)
8:19:34 AM: error There was an error
8:19:34 AM: not finished source and transform nodes - 449.122s
8:19:34 AM: not finished  gatsby-source-wordpress  fetching nodes - 449.064s - 3941 total
8:19:34 AM: not finished  gatsby-source-wordpress  creating nodes - 50.799s
8:19:34 AM: not finished  gatsby-source-wordpress  MediaItem - 50.798s - fetched 1954
8:19:34 AM: not finished Downloading remote files - 50.005s`

Any thoughts on the issue?

Thanks
Chris

**Comment by szmarczak** [comment]
`ECONNRESET` means the connection was reset. Your network connection might got disrupted.

**Comment by maggie0002** [comment]
> Thanks, it turned out to be Cloudflare's security module. For some reason it resets the connection.

What did you have to change in your Cloudflare configuration to get it to work?
